server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jerrylz.entities
