server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
eureka:
  instance:
    hostname: cloud-gateway-server
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka